# Generated by Django 5.1.6 on 2025-04-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='auto_note',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='correction',
            name='feedback_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
