# Generated by Django 5.1.6 on 2025-04-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_correction_auto_note_correction_feedback_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('prof', 'Professeur'), ('etudiant', 'Étudiant'), ('admin', 'admin')], default='etudiant', max_length=10),
        ),
    ]
