# Generated by Django 5.1.6 on 2025-04-23 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_correction_date_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('etat', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_auto', to='api.exercice')),
            ],
        ),
    ]
